name: PHP 7.2

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '15 8 * * *'

jobs:
  test:
    name: PHP 7.2
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Update
        run: sudo apt-get update

      - name: Install required dependencies
        run: sudo apt-get install gcc make autoconf bison re2c pkg-config libxml2-dev libsqlite3-dev libcurl4-gnutls-dev uuid-dev libssl-dev

      - name: Clone php source
        working-directory: ./ext/php-build
        run: git clone https://github.com/php/php-src.git

      - name: Checkout to PHP 7.2.22
        working-directory: ./ext/php-build/php-src
        run: git checkout PHP-7.2.22

      - name: Build PHP Config
        working-directory: ./ext/php-build/php-src
        run: ./buildconf --force --debug

      - name: Create Build destinations
        working-directory: ./ext/php-build
        run: mkdir 7.2.22 && mkdir 7.2.22/php-ini

      - name: Configure PHP
        working-directory: ./ext/php-build/php-src
        run: ./configure --enable-debug --enable-maintainer-zts --with-openssl --prefix=$PWD/../7.2.22 --with-config-file-path=$PWD/../7.2.22/php-ini

      - name: Build PHP
        working-directory: ./ext/php-build/php-src
        run: make -j2 # github actions is executed at 2 core machines

      - name: Install PHP
        working-directory: ./ext/php-build/php-src
        run: make install

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Initialize extension
        working-directory: ./ext
        run: ./bin/init.sh
        env:
          PHP_UAMQP_PHP_EXECUTABLE: php-build/7.2.22/bin

      - name: Build extension
        working-directory: ./ext
        run: make
        env:
          PHP_UAMQP_PHP_EXECUTABLE: php-build/7.2.22/bin

      - name: Run testsuite
        working-directory: ./ext
        run: make test
        env:
          PHP_UAMQP_TEST_SB_HOST: ${{ secrets.ENV_PHP_UAMQP_TEST_SB_HOST }}
          PHP_UAMQP_TEST_SB_POLICY_KEY: ${{ secrets.ENV_PHP_UAMQP_TEST_SB_POLICY_KEY }}
          PHP_UAMQP_TEST_SB_POLICY_NAME: ${{ secrets.ENV_PHP_UAMQP_TEST_SB_POLICY_NAME }}
          PHP_UAMQP_TEST_SB_DESTINATION: "github-test-php72"
          PHP_UAMQP_PHP_EXECUTABLE: php-build/7.2.22/bin
          PHP_UAMQP_TEST_FUNCTIONAL_SKIP: 0
          NO_INTERACTION: 1

      - name: Dump outptup from failed tests
        if: failure()
        run: find . -name "*.out" -type f -exec cat {} \;
        working-directory: ./ext/tests